apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  selector:
    app: healthcare
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 32000
  type: NodePort
